### ISSUE TITLE
Cropped output

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#10]
Capturing sometimes crops the output.

![review](https://cloud.githubusercontent.com/assets/2152766/8634321/ccd3dc00-27ec-11e5-8099-ed0d80834d69.gif)

Somehow due to the independent panel not getting the correct size.

**Comment by BigRoy** [comment]
In older versions (much much older) having a window over the viewport being playblasted also meant having it being cut off in the output. Not sure if relevant?

**Comment by mottosso** [comment]
No, this isn't that. That wasn't related to Maya anyway, that was a Windows thing, and the fact that pre-Aero (win 7), windows behind other windows weren't drawn by the OS. Add to that that Maya takes screenshots of a window for it's playblasts, and you've got a recipe for disaster.

This is much improved with the off-screen playblasts, which is completely in memory and independent of the drawn windows.

**Comment by BigRoy** [comment]
> No, this isn't that. That wasn't related to Maya anyway, that was a Windows thing,

Great. Just checking.

---

Would be great to find a piece of code that reproduces the issue with the cropping so we can track it down. Or is it only on random occasions?

**Comment by mottosso** [comment]
It's random. :( Or at least, as far as I can tell at.

It usually happens for the first capture, so it might be some initialisation thing. I haven't looked too closely at it.

**Comment by mottosso** [comment]
Haven't seen this happen in a while, might be fixed in some of the more recent updates.

Closing until it reapperas.
