### ISSUE TITLE
Redesign option classes

### ISSUE THREAD

**Issue by BigRoy** [mottosso/maya-capture#14]
I would like to propose another design for our option classes like `ViewportOptions` and `CameraOptions`.

### Goal

Streamline how options are passed onto the `capture` and `snap` functions and how these Option classes are designed.

#### Currently

Currently each Options class needs its own context manager like `_applied_camera_options()` and `_applied_viewport_options` alongside its options class like `CameraOptions` and `ViewportOptions`.

#### Proposed implementation

We create a base class for `Options` that sets some rules on how options are applied and accompany this with our own context manager.

```python
class Options(object):
    def set(self, panel, camera):
        """Applies the options for the panel and camera."""
        pass

    @staticmethod
    def current(panel, camera):
        """Return the options for the currently defined user-settings"""
        pass

@contextlib.contextmanager
def _options(options, panel, camera):
    """Context-manager to temporarily assign the options and afterwards restore the original"""
    original = options.current(panel, camera)
    options.set(panel, camera)
    yield
    original.set(panel, camera)
```

For example the current viewport options context manager could be removed and the `ViewportOptions` class could become:

```python
class ViewportOptions(Options):
    """Viewport options for :func:`capture`"""

    useDefaultMaterial = False
    wireframeOnShaded = False
    displayAppearance = 'smoothShaded'

    # Visibility flags
    nurbsCurves = False
    nurbsSurfaces = False
    polymeshes = True
    subdivSurfaces = False
    cameras = False
    lights = False
    grid = False
    joints = False
    ikHandles = False
    deformers = False
    dynamics = False
    fluids = False
    hairSystems = False
    follicles = False
    nCloths = False
    nParticles = False
    nRigids = False
    dynamicConstraints = False
    locators = False
    manipulators = False
    dimensions = False
    handles = False
    pivots = False
    textures = False
    strokes = False

    def set(panel, camera):
        """Applies the options for the panel and camera."""
        options = _parse_options(self)
        cmds.modelEditor(panel,
                                    edit=True,
                                    allObjects=False,
                                    grid=False,
                                    manipulators=False)
        cmds.modelEditor(panel, edit=True, **options)

    @staticmethod
    def current(panel, camera):
        """Return the options instance for the currently defined user-settings"""
        
        viewport_options = ViewportOptions()
        options = _parse_options(viewport_options)
        
        for key in options:
            kwargs = {key: True}
            value = cmds.modelEditor(panel, query=True, **kwargs)
            setattr(viewport_options, key, value)
            
        return viewport_options
```

### Decision

**Pros**
This way we have:

- unified design for `Options` classes
- less context managers
- it's clear how to use the options classes on their own `Options.set(panel, camera)`

**Cons**
The options classes will all have access to *panel* and *camera* even though they might not need to.

**Comment by BigRoy** [comment]
Maybe it's clearer to have the `set()` method be renamed to `apply()`. The proposition stays the same.

**Comment by mottosso** [comment]
I'm not sure about this. These classes are mainly data structures and will likely never need to change. Embedding logic into them means they might, which means there's a mixture of static and non-static values.

I actually don't mind context managers, and think they are rather clear about what they do, and as they are "protected" (i.e. starting with an underscore) I think it's pretty clear that they are not meant to be used on their own. It's unlikely that the amount of context managers will ever increase as well, as they already encompass all possible settings Maya has to offer in regards to playblasting.

**Comment by BigRoy** [comment]
It's less about simplifying and more about the possibilities of extending functionalities in the form of custom options. 

I noticed there is a `DisplayOptions` class that mentions *anti-alias* and *backgroundColor* in the docstrings. This will likely need to get its own additional context manager? And also its own argument within `capture()`.

What happens if we want to extend settings for a possible custom renderer? To stay open for such custom features we can use it like this:

```python
viewport_options = ViewportOptions.current()
display_options = DisplayOptions.current()
capture.capture(options=[viewport_options, display_options])
```

If someone needs to extend it for its own renderer (or one from a plug-in) they only have to implement their own `Options` class.

---

Currently if I just wanted to playblast with my current settings I would have to write my own code to retrieve the currently set values from Maya (since our options don't provide that). By default `capture()` overrides your viewport settings to a default defined in the options class making it even harder to playblast with the currently defined settings.

Another benefit of applying only the options provided is that it defaults to what the user sees in the viewport, it makes sense to override it only when we provide the options?

**Comment by mottosso** [comment]
> Another benefit of applying only the options provided is that it defaults to what the user sees in the viewport, it makes sense to override it only when we provide the options?

This is actually counter to what I'd like `capture` to do.

`capture` defines it's own defaults to reduce any dependency on "current" settings, which are never guaranteed to be the same across sessions, and especially not workstations/users/studios.

It's important that wherever you run `capture()` the results are always identical, with no coupling to the current session. How else can you program with it, and produce reliable programs?

> It's less about simplifying and more about the possibilities of extending functionalities in the form of custom options.

"Do one thing, and do it well"

`snap()` is already breaching this, especially since we didn't model a use-case for it beforehand. Without a real use-case, this sounds too close to over-engineering. "What ifs" aren't enough.

**Comment by BigRoy** [comment]
Let me implement #1 and #2 and see how far we get. 
Would we also implement Options for *Viewport 2.0* and *High Quality Renderer*?

**Comment by mottosso** [comment]
Ok.

> Would we also implement Options for Viewport 2.0 and High Quality Renderer?

Yes, those would be the `DisplayOptions`. Do you think this would also be a good place to specify *which* viewport to use as well?

```python
display_opts = DisplayOptions()
display_opts.viewport = "viewport2.0"
display_opts.viewport = "highqualityrenderer"
```

Are these names defined somewhere else, like in the Maya API? Ideally I'd prefer reusing those names, as opposed to making new ones up like above. Unless they are too cryptic.

**Comment by BigRoy** [comment]
They seem to be rather cryptic. And according to Maya they would belong to `ViewportOptions` because they are related to the Viewport, see [*modelEditor*](http://help.autodesk.com/cloudhelp/2015/ENU/Maya-Tech-Docs/CommandsPython/modelEditor.html#flagrendererName).

All we would have to do is add the attribute `rendererName` to `ViewportOptions`.

**Comment by BigRoy** [comment]
Note how the implementation for #2 in required to add in an extra argument for `capture()` plus nest the *with* statements one level deeper.

Also see how specific the settings are to apply and retrieve for these options.

**Comment by BigRoy** [comment]
I'll leave the open issues for now since I've pushed many changes today. I'll let you have some time to go through the latest code and for example implement the viewport 2.0 options in your own way. That way I can see the alternative you would like as opposed to what I'm proposing here. 

Do you think that would be a good way forward?

**Comment by mottosso** [comment]
Yes, that sounds great. Phew. :)

**Comment by BigRoy** [comment]
Had a quick look at the possibilities with the redesign proposed. Consider it **pseudo-code** since I set it up so far without running it, but you can have a look at my [`options` branch](https://github.com/BigRoy/maya-capture/tree/options/capture) here.

The code does slim down a bit already and it opens the door to much more option classes (and even allows extending the context manager with your own custom options.) In theory the `isolate_view` could become its own Options class without a hitch!

Still think it has some interesting upsides going forward.

Note that I also changed it into a package as opposed to a single module to separate the options out from the core api. `__init__.py` solely gives access to `capture()` and `snap()` to keep things simple.

**Comment by mottosso** [comment]
Could we start using these features, before we implement anything else? It smells too much like overengineering at the moment and part of me would rather stick with `cmds.playblast` if it keeps getting more complex.

**Comment by BigRoy** [comment]
> Could we start using these features, before we implement anything else?

Of course. I just wanted to have a look at whether it would slim down and simplify the code or whether it would become a mess instantly. It seems to be a good solution when we find ourselves with many options to be implemented.

It's definitely not something I just want to push through *'just because'*.

> It smells too much like overengineering at the moment and part of me would rather stick with cmds.playblast if it keeps getting more complex.

Definitely! I think we could even do the exact opposite. Make a single `Options` class as opposed to the different ones for Viewport, Display and Camera. In the end they are all just `PlayblastOptions`?

So bringing it back to something like:

```python
class PlayblastOptions(Options):
    """Playblast options for :func:`capture`"""

    useDefaultMaterial = False
    wireframeOnShaded = False
    displayAppearance = 'smoothShaded'

    # Visibility flags
    nurbsCurves = False
    nurbsSurfaces = False
    polymeshes = True
    subdivSurfaces = False
    cameras = False
    lights = False
    grid = False
    joints = False
    ikHandles = False
    deformers = False
    dynamics = False
    fluids = False
    hairSystems = False
    follicles = False
    nCloths = False
    nParticles = False
    nRigids = False
    dynamicConstraints = False
    locators = False
    manipulators = False
    dimensions = False
    handles = False
    pivots = False
    textures = False
    
    # Display flags
    displayGradient = True
    background = (0.631, 0.631, 0.631)
    backgroundTop = (0.535, 0.617, 0.702)
    backgroundBottom = (0.052, 0.052, 0.052)
    
    # Camera flags
    displayGateMask = False
    displayResolution = False
    displayFilmGate = False
```

This would also mean there's no need for the nested `with` statement we have going in `playblast()` and reduce the option arguments to a single one basically `options`. Could bring back some simplicity?

On the other hand it might make the `context manager` code a bit more complex?
What do you think?

**Comment by mottosso** [comment]
The only thing that matters to me is the interface towards the user. I'm not sure think the code-base is large enough to cause trouble with maintenance, on the contrary I think we'll save more time and effort in the long run in keeping things straightforward, rather than optimal in terms of reuse or less lines of code. This is also a reason not to divide functionality into modules.

If this was for Pyblish, or some other larger library, where maintenance is key, I'd be with you, this sounds like a reasonable next step. But do you think it also makes sense in this case? The context managers make it very clear what's going on, even if they cause a bit of indentation in the code. The current option classes may not be optimal, but they are obvious (IMO).

In fact, I might even opt for discarding classes altogether, and go for something like this.

```
capture(view_options={
  "displayResolutionMask": True,
  "background": (0.6, 0.1, 0.1)
})
```

capture.py does very little, and I'd like to keep it that way. It won't do everything, but I think that's ok.

**Comment by BigRoy** [comment]
> In fact, I might even opt for discarding classes altogether, and go for something like this.

Even better! As long as its clear what attributes translate into which *maya terminology or attributes*. I think those that will get involved with messing with the values will look for them coming from the Maya terminology (or even a search on how it's done in Maya).

**Comment by mottosso** [comment]
> As long as its clear what attributes translate into which maya terminology or attributes.

Yeah, that stuff is key.

I'd be happy for you to have a look at replacing the classes with dictionaries.

**Comment by BigRoy** [comment]
Hmm, I don't think this is the most urgent issue. Maybe tackle the other issues to see what functionality we need in the end and then let's have a look whether dictionaries is still the best way to tackle it. Maybe we stumble upon something even simpler as we go?

At this point any of the presented methods is fine for me still.

**Comment by mottosso** [comment]
This has been implemented and breaks backwards compatibility.

Rather than creating and passing these classes, you now just pass a dict of the contents.

```python
# before
options = DisplayOptions()
options.displayGradient = False

# now
options = {"displayGradient": False}
```

Which means that all arguments to `capture()` are now passable as a one-off.

```python
capture.capture(**{
    "width": 320,
    "height": 240,
    "camera_options": {
        "displayGateMask": False
    },
    "viewport_options": {
        "wireframeOnShaded": True
    },
    "display_options": {
        "displayGateMask": False
    }
})
```

Which means you can start saving these dictionaries (e.g. to disk) and make [presets](https://github.com/mottosso/maya-capture/issues/27).

**Comment by BigRoy** [comment]
Sweet. Is there a way to retrieve the currently active values?

Will look over the code tomorrow

**Comment by BigRoy** [comment]
Had an additional idea regarding this where it's also easy to retrieve the current state to define presets.

This would be the `parse_view (camera, panel)` method that returns an options dict. Than there's a method that sets the view with those options `set_view (camera, panel, options)`

The context manager that sets the view during playblast would then become:

```python
@contextlib.contextmanager
def set_view_context (camera, panel, options):
    original = parse_view (camera, panel)
    try:
        set_view (camera, panel, options)
        yield
    except:
        set_view (camera, panel, options)
```

Other benefits are:

- it exposes methods to parse current state for use of presets
- also allows TD to use the methods to apply the options state for other purposes easily (e.g. for debugging)
- short and simple context manager


*typed on phone, sorry for any possible typos*

**Comment by mottosso** [comment]
> Sweet. Is there a way to retrieve the currently active values?

No, I was expecting a pull request on that. Didn't you guys build that somewhere?

> This would be the parse_view (camera, panel)

Let's continue this conversation in the #27 (presets) thread, seems related.

**Comment by BigRoy** [comment]
> No, I was expecting a pull request on that. Didn't you guys build that somewhere?

Only discussed. Didn't implement. Will do so upon your latest commits so it fits right in. Coming today or tomorrow.

**Comment by mottosso** [comment]
> Only discussed. Didn't implement. Will do so upon your latest commits so it fits right in. Coming today or tomorrow.

Sweet beans!
