### ISSUE TITLE
Independent panels remain in Maya session

### ISSUE THREAD

**Issue by BigRoy** [mottosso/maya-capture#15]
Whenever a `snap()` or `capture()` is triggered the independent panel that is created remains in the Maya session and isn't deleted. This usually doesn't trigger any problems since the panels get disabled, but it does show in the UI as panels with no names.

They show in the viewport under *panels > panel > ...*

It's a minor inconvenience but would be great to get solved.

To make this cleaner I think it's best to create the panel with a name so it's identifiable, something like labeling it `capturePanel`. So if it's not deleted for some reason we at least see it show up with that name.

This could also be the problem responsible for the 5 mb RAM cost per capture as noted in the code:
```python
    try:
        yield panel
    finally:
        # Ensure window always closes
        # .. note:: We hide, rather than delete as deleting
        #   causes the focus to shift during capture of multiple
        #   cameras immediately after one another. Altering the
        #   visibility doesn't seem to have this effect, it does
        #   however come at a cost to RAM of about 5 mb per capture.
        cmds.window(window, edit=True, visible=False)
```

Looking at this note in the code I'm wondering if it's an issue to delete the panel in between playblasts?

**Comment by mottosso** [comment]
> Looking at this note in the code I'm wondering if it's an issue to delete the panel in between playblasts?

Yes, as it says, it causes trouble with multiple captures.

If you can find a solution to this, that would be great, but as you say, it's not that great of a problem.

**Comment by BigRoy** [comment]
How can I notice the *focus shifting behavior*? Not entirely sure what to look out for.

**Comment by mottosso** [comment]
Have you tried capturing from two or more cameras sequentially? I can't remember how I encountered it, but there must have been a reason. Possibly when something else was happening inbetween captures, like modifying the scene.

**Comment by BigRoy** [comment]
Ah, now I notice what is going on. It shifts focus to a modelPanel in the background so stops previewing the playback in the independent panel.

Will have a look at working around that. Deleting the panel does fix the 5 mb RAM leak per capture.

**Comment by BigRoy** [comment]
Squashed it. Shall I set up a Pull Request?

**Comment by mottosso** [comment]
Ah, that's perfect, yes please do.
