### ISSUE TITLE
Output resolution mismatch

### ISSUE THREAD

**Issue by BigRoy** [mottosso/maya-capture#17]
I've been doing some captures/snaps and noticed the size wasn't the exact render resolution but slightly smaller.

For example:

- *1920x1080* ends up being *1916x1074*.
- *320x240* ends up being *316x234*.

It seems to have mismatch of being 4 pixels too small in width and 6 too small in height.

---

Also did a quick capture of *4096x4096* which ended up being *4092x1441*. I thought this height was being cropped because it reaches the limit of the H264 encoding, but the same happened with `snap()` (image, png). This made me think it happens because the panel reaches the size of my screen in height.

**Comment by mottosso** [comment]
Interesting, sounds like the panel is being given the fixed size, but that the border is subtracted from the final output. Sounds like a bug.

**Comment by BigRoy** [comment]
Might be better to *overcompensate* with the independent panel (like +10 in X and Y) and set the width and height in the `maya.cmds.playblast` command? This is to ensure it fits the panel no matter what OS? (I'm assuming there might be differences between OS on how windows/panels appear)

**Comment by mottosso** [comment]
Sure, if that's really what it is, have you found a way to confirm that it is the OS that causes the subtraction?

Can never rely on how some might customise their native windowing systems, like having much larger borders.

**Comment by BigRoy** [comment]
> Sure, if that's really what it is, have you found a way to confirm that it is the OS that causes the subtraction?

Without supplying a width and height to the playblast command it uses the size of the panel. So I assume it's the padding of the window/panel. Note that when supplying width/height to the playblast command you still need to ensure it at least fits the panel when not rendering off-screen, that's why I stated overcompensating could be a best option. (It would show small borders around the viewport in the panel during the playblast if I'm correct)

**Comment by BigRoy** [comment]
Upside to https://github.com/BigRoy/maya-capture/commit/b7de34ef7e2965fdefabc1498aa5774c0352aa64 is that it also gives the usual `playblast` warning when viewport doesn't fit on-screen for rendering that the output gets clamped. Before output was clamped without notice since it wasn't specified for the playblast command.

**Comment by mottosso** [comment]
Has this been fixed?

**Comment by BigRoy** [comment]
Haven't seen this happen anymore since the padding was introduced.
