### ISSUE TITLE
Flag for background color

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#2]
Currently uses the current background color, but ideally, all playblast within a particular project should have the same color.

**Comment by BigRoy** [comment]
Got this implemented under `DisplayOptions`. Note that `backgroundTop` and `backgroundBottom` are used when `displayGradient` is True and `background` is used when `displayGradient` is False.

The colors are 0 to 1 values for RGB.
The default settings for `DisplayOptions` are the default Maya viewport colors. Currently it defaults to using the gradient.

**Comment by mottosso** [comment]
Works good!
