### ISSUE TITLE
Undo after capture/snap goes to frame 1 instead of preserving the previous frame.

### ISSUE THREAD

**Issue by BigRoy** [mottosso/maya-capture#21]
The `maya.cmds.playblast` command seems to suffer from an undo bug, see [here](http://forums.cgsociety.org/showthread.php?f=89&t=1296751). Upon undoing the command it'll revert back to frame 1 as opposed to going back to the frame it was before playblasting.

A workaround/bugfix is to set the current time before calling the playblast command, like so:

```python
maya.cmds.currentTime(maya.cmds.currentTime(q=1))
```

**Comment by mottosso** [comment]
I'm thinking a context-manager to automatically reset the time after each capture would be good here. No command should really mess with state, unless it's intended to.

**Comment by BigRoy** [comment]
> I'm thinking a context-manager to automatically reset the time after each capture would be good here. No command should really mess with state, unless it's intended to.

That's a separate issue, since that's unrelated to the undo bug of the playblast command? Also that would mean setting the time afterwards instead of beforehand?

**Comment by mottosso** [comment]
But wouldn't that nullify this problem? If `capture` never altered the frame to begin with?

**Comment by mottosso** [comment]
Would it still revert to frame 1 you think? :O

**Comment by BigRoy** [comment]
> Would it still revert to frame 1 you think? :O

I think so, yes. But I'm thinking in the form of "undo chain". The current time is set afterwards thus gets processed first when undo'ing. Since the playblast has the issue where it resets to frame 1 on undo, the issue would then still be present.

But I'll have a look!

**Comment by BigRoy** [comment]
Yup, as I thought, the issue would still be there. :(

**Comment by BigRoy** [comment]
This is fixed with https://github.com/BigRoy/maya-capture/commit/f4a220762aee7a284fa485d2d7f8c3fbbe415791.

> I'm thinking a context-manager to automatically reset the time after each capture would be good here. No command should really mess with state, unless it's intended to.

See #23.

**Comment by mottosso** [comment]
Aweseome!
