### ISSUE TITLE
Capture does not record the exact resolution gate, but includes overscan

### ISSUE THREAD

**Issue by BigRoy** [mottosso/maya-capture#22]
The camera's overscan is included in the screen capture. This means the output is not the same as it would be when you would perform a render of the shot.

Setting the camera's overscan to 1.0 (could be done through CameraOptions) would fix this.

Also by default `CameraOptions` are not used but skipped. To allow the overscan to default to 1.0 this should be used by default.

**Comment by mottosso** [comment]
+1

I think this should always happen. The Gate is what matters.
