### ISSUE TITLE
CameraOptions doesn't contain chart/action overlay settings

### ISSUE THREAD

**Issue by BigRoy** [mottosso/maya-capture#25]
The CameraOptions is missing some attributes that influence the way an output looks.

For example those that draw a guide/overlay over the viewport:

```python
displayFieldChart
displaySafeAction
displaySafeTitle
displayFilmPivot
displayFilmOrigin
```

I assume we want to include those settings and have them turned off by default.
What's the preferred expected behavior?

**Comment by mottosso** [comment]
I'd expect the default values to be those that come with a freshly installed Maya on a plain `persp` camera, similar to how the Background currently reverts to that awful gradient currently. Not ideal perhaps, but most expected I think.

**Comment by BigRoy** [comment]
Upon opening a new scene or creating a new camera they are all `False` so I'll set the values accordingly. Great!

**Comment by mottosso** [comment]
+1

**Comment by BigRoy** [comment]
Also fixed and merged with https://github.com/mottosso/maya-capture/pull/24
