### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#27]
Continuing from discussion in #1.

### Goal

Support saving and loading of presets.

### Implementation

Implement a function to read settings from the currently active view in such a way that the output can be directly fed into the `capture()` function.

**Example**

```python
import json
from maya import cmds

from capture import capture, ViewportOptions, CameraOptions

def parse_active_view():
    """Parse active view for settings"""
    panel = cmds.getPanel(withFocus=True)
    assert "model" in panel, "No active viewport"
    camera = cmds.modelPanel(panel, query=True, camera=True)
    camera_shape = cmds.listRelatives(camera, shapes=True)[0]

    return {
        "camera": camera,
        "width": cmds.getAttr("defaultResolution.width"),
        "height": cmds.getAttr("defaultResolution.height"),
        "camera_options": type("CameraOptions", (object, CameraOptions,), {
            "displayFilmGate": cmds.getAttr(camera_shape + ".displayFilmGate"),
            "displayResolution": cmds.getAttr(camera_shape + ".displayResolution"),
            "displaySafeAction": cmds.getAttr(camera_shape + ".displaySafeAction"),
        }),
        "viewport_options": type("ViewportOptions", (object, ViewportOptions,), {
            "useDefaultMaterial": cmds.modelEditor(panel, query=True, useDefaultMaterial=True),
            "wireframeOnShaded": cmds.modelEditor(panel, query=True, wireframeOnShaded=True),
            "displayAppearance": cmds.modelEditor(panel, query=True, displayAppearance=True),
        })
    }

# Create preset   
preset = parse_active_view()

# Use preset
capture(**preset)
```

**Comment by mkolar** [comment]
This works quite well!

I've done some testing and after I added a few more options it always caught current viewport state correctly.

Funnily I think It's actually keeping all the viewport 2.0 options automatically. AO, MB, AA and DOF all work. If I turn them on in the viewport, they look correct in the playblast too.

```python
import json
from maya import cmds

from capture import capture, ViewportOptions, CameraOptions

def parse_active_view():
    """Parse active view for settings"""
    panel = cmds.getPanel(withFocus=True)
    assert "model" in panel, "No active viewport"
    camera = cmds.modelPanel(panel, query=True, camera=True)
    camera_shape = cmds.listRelatives(camera, shapes=True)[0]

    return {
        "camera": camera,
        "width": cmds.getAttr("defaultResolution.width"),
        "height": cmds.getAttr("defaultResolution.height"),
        "camera_options": type("CameraOptions", (object, CameraOptions,), {
            "displayFilmGate": cmds.getAttr(camera_shape + ".displayFilmGate"),
            "displayResolution": cmds.getAttr(camera_shape + ".displayResolution"),
            "displaySafeAction": cmds.getAttr(camera_shape + ".displaySafeAction"),
        }),
        "viewport_options": type("ViewportOptions", (object, ViewportOptions,), {
            "useDefaultMaterial": cmds.modelEditor(panel, query=True, useDefaultMaterial=True),
            "wireframeOnShaded": cmds.modelEditor(panel, query=True, wireframeOnShaded=True),
            "displayAppearance": cmds.modelEditor(panel, query=True, displayAppearance=True),
            "displayTextures": cmds.modelEditor(panel, query=True, displayTextures=True),
            "displayLights": cmds.modelEditor(panel, query=True, displayLights=True),
            "shadows": cmds.modelEditor(panel, query=True, shadows=True),
            "xray": cmds.modelEditor(panel, query=True, xray=True),
        }),
        "display_options": type("DisplayOptions", (object, DisplayOptions,), {
            "background": cmds.displayRGBColor('background', q=True),
            "backgroundTop": cmds.displayRGBColor('backgroundTop', q=True),
            "backgroundBottom": cmds.displayRGBColor('backgroundBottom', q=True),
            'displayGradient': cmds.displayPref(dgr=True, q=True),
        }),
    }
```

**Comment by mottosso** [comment]
Sweet. Feel free to add it to the source and we'll keep adding to it until it's complete.

Just a note, to save this preset to JSON, we'll need to convert the option classes into pure dictionaries too. But that can come later.

**Comment by BigRoy** [comment]
Just to note: it's keeping the viewport 2.0 settings because `capture` isn't overriding it yet with its default. Based on @mottosso intentions that might just be unexpected behavior (even though I think it makes more sense to have that workflow overall; though this has been discussed).

Also, ditch the option classes indeed and we're quite far along. Did you push this to your fork @mkolar? I'd be happy to have a look at refactoring a bit.

**Comment by mottosso** [comment]
> it's keeping the viewport 2.0 settings because capture isn't overriding it yet with its default. 

Ah, interesting. Yes, that is unexpected, we'll need to squash that!

**Comment by BigRoy** [comment]
Also since it hasn't been mentioned yet I'd rather see a `parse_view (camera, panel)` where `parse_active_view` is purely using that to provide a convenience function.

I think this way we can retrieve the data in a much more explicit manner.

**Comment by mkolar** [comment]
>Did you push this to your fork @mkolar? 

I did. Go for it if you want.

> Ah, interesting. Yes, that is unexpected, we'll need to squash that!

For the time being I'm loving this particular 'bug' :smile:

**Comment by mottosso** [comment]
> For the time being I'm loving this particular 'bug' :smile:

Haha, man. Why aren't you guys just using `cmds.playblast`? Doesn't it do exactly this?

Good luck getting consistency, counting on artists having "Viewport 2" currently active when they submit their playblasts.

**Comment by mottosso** [comment]
> That removes the changing logic from the capture () function into a single call. 

What changing logic?

**Comment by mkolar** [comment]
> Why aren't you guys just using cmds.playblast? 

For many projects, we want full control, for some, partial control. Capture is the one tool to rule them all ;)

**Comment by BigRoy** [comment]
I think the rule of partial control is really valid. We want to "fit" it with the requirements. Toggling visibility to polygons only might just be wrong if we are doing lots of dynamics that require a view. Not really a problem, but it shouldn't mean messing with tons of code to get it right. Once the options are simplified I might start a `capture-extended` repo or alike that has a preset manager of sorts.

I can totally see the benefits of controlling everything. We just need an easy way to "choose" the right setting for the job. With the amount of settings there are currently it's quite a lot of work to set up a default of your own for a project.

> What changing logic?

The setting of viewport settings. This "changing" is what I meant and is I think currently handled as a couple of nested with statements. (Haven't delved into latest code yet; might have a look tonight)

**Comment by mottosso** [comment]
Ok, this is now implemented.

**Example**

```python
preset = {
    "width": 320,
    "height": 240,
    "camera_options": {
        "displayGateMask": False
    },
    "viewport_options": {
        "wireframeOnShaded": True
    },
    "display_options": {
        "displayGateMask": False
    }
}

capture.capture(**preset)
```

**Comment by mkolar** [comment]
Beautiful

**Comment by mottosso** [comment]
:) Glad you like it.

**Comment by BigRoy** [comment]
Just did a commit with parsing the view, see https://github.com/BigRoy/maya-capture/commit/c76fc2e069b741942273a55d5e95a4e0e363f460.

Possible usage:

```python
import capture

options = capture.parse_active_view()
capture.capture(**options)
```

And more specific from TD perspective:

```python
import capture

options = capture.parse_view(panel, view)
```

Note that the `parse_view()` does not parse things like frame range or resolution. It currently only parses the `viewport_options`, `camera_options` and `display_options`.

Also note that this current implementation of the `applied_options()` context manager will always set all available settings even if the options provided doesn't change all of them. This can be easily fixed, but I just wanted to showcase the behavior and changes thus far.

**Comment by mottosso** [comment]
Looks very good! Could you submit a PR? It's easier to speak of implementation and lines of code there.
