### ISSUE TITLE
RuntimeError: Unable to create movie file

### ISSUE THREAD

**Issue by BigRoy** [mottosso/maya-capture#29]
I'm getting an error when running capture's default settings.

```python
import capture
capture.capture()
```

This results in an error like:

```
# Error: Unable to create a movie file. It may be open by another application.
# Unable to copy the video to its final destination. Check if the path is accessible.
# Traceback (most recent call last):
#   File "<maya console>", line 6, in <module>
#   File "C:\Work\pipeline\dev\git\maya-capture\capture.py", line 159, in capture
#     **playblast_kwargs)
# RuntimeError: Unable to create a movie file. It may be open by another application.
# Unable to copy the video to its final destination. Check if the path is accessible. # 
```

I'm assuming this is a permissiong thing. I've seen this happen before when rendering to a Quicktime format from Maya. Some things that were the problems then:

- Quicktime is not available on your system. Install Quicktime.
- Quicktime renders into your %TMP% folder after which it copies the file. As such ensure that the `%TMP%` is correctly set up in your environment variables to a folder to which your user (that started Maya) has access and permissions. (Not sure whether Quicktime used `%TEMP%` or `%TMP%`)

Will have a look if one of the above fixes it on my laptop.
Posting this here so it can also be found by others (even if I happen to fix this quickly).

---

Windows 10
Maya 2016

**Comment by BigRoy** [comment]
For completeness sake, in this case for me installing Quicktime and then rebooting fixed it partially for me.

```python
import capture
capture.capture()
```

Now the above at least runs through the timeline to actually do a playblast. Yet it stills seems to give errors. Maya also spams out some additional commands it triggers (like `sysFile -copy`)

```python
sysFile -copy "C:\Users\Roy\AppData\Local\Temp\blast2.mov" "C:/Users/Roy/AppData/Local/Temp/movie_2.mov";
// Result: 0 // 
# Warning: command failed: "" # 
currentTime 120 ;
# Error: Unable to copy the video to its final destination. Check if the path is accessible. # 
```

This might be a backward/forward slash problem looking at the `sysFile -copy` line. Got to run now, maybe I can have a better look tonight or tomorrow morning.

**Comment by mottosso** [comment]
Can you reproduce this with `cmds.playblast`?

**Comment by BigRoy** [comment]
Yes, same is happening with `cmds.playblast` in Quicktime format. Looking on the internet it seems to be a Maya 2016 issue as mentioned [here](http://forums.autodesk.com/t5/animation-and-rigging/playblast-error-maya-2016/td-p/5622302).

I'm on Maya 2016 SP4 and noticed something in the changelog for SP5:

```
MAYA-55165 	Playblasts to Quicktime format cannot save to temp directory and fails 
```

I'm updating now to see if that fixes it.

**Comment by BigRoy** [comment]
Fixed in Maya 2016 SP5.

**Comment by kosam0913** [comment]
install QuickTime will help
[https://3dcg.comaroku.com/maya-playblast-mov/](url)
