### ISSUE TITLE
Capture selected camera(s)

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#3]
Provide a menu-option for capturing the currently selected camera(s), captured using the current range and resolution, using the scene-name for output (if scene is saved).

**Comment by BigRoy** [comment]
This might be better preserved for something more "extended" like an interface? 

Also capture seems quite compact and forced to set a specific default when no settings are applied so I'm thinking it might be hard to have a menu-item be usable for many as a one off button.

Would this suit a `capture-gui` separation? Or `capture-extended`?

**Comment by BigRoy** [comment]
With #32 this could be added as a sample in the readme?

**Comment by mottosso** [comment]
Yeah
