### ISSUE TITLE
Playblast highlighted time range by default when time range is selected

### ISSUE THREAD

**Issue by BigRoy** [mottosso/maya-capture#35]
Should the default be (when no start and and frame provided as arguments) and a "selection" in the time slider is active that `capture()` would take that time range instead of the start and end frame of the time slider bar.

This would make the behavior somewhat closer to Maya's default playblast where you could highlight a small area in your timeline and that playblast only that.

As such behavior would become:

- if `start_frame` and `end_frame` provided as arguments use that
- else if time slider range highlighted use that
- else use min/max of time slider.

**Comment by mottosso** [comment]
I'm not sure.

capture to me is the opposite of interactive, I'm not sure this leads to anything good. On the other hand, it is neat. But is it expected? You're saying `cmds.playblast` does this?

**Comment by BigRoy** [comment]
> You're saying cmds.playblast does this?

Had a quick look. No, it doesn't.

But it does do it with the menu item of `playblast` or right-click timeline and `playblast` when the time range is set to time slider (default).

---

I opened this issue because we've been using our own playblast tool in-house (not `capture` at the time) and artists asked about the possibility of enabling this feature where highlighting a part of the time range would only playblast that.

**Comment by mottosso** [comment]
> Maybe it should be an additional argument? Like use_highlighted_range

I think a menu with `capture(start_frame=..., end_frame=...)` where you are getting those numbers from the current selection should suffice.
