### ISSUE TITLE
depthOfFieldPreview doesn't exist

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#38]
Getting an error on an unavailable option for `depthOfFieldPreview`, removing this from the source dict solves the issue.

**Comment by BigRoy** [comment]
Interesting. Is this a Maya version specific feature? Are you on `2015`? I tested this in `2016` and it works fine. 

It's also the command the GUI itself uses when enabling depth of field preview (even though it's not stated in `maya.cmds.modelEditor` docs of 2016.

**Comment by mottosso** [comment]
I'm on 2015 yes. We should try and keep compatibility with 2013 upwards.

**Comment by BigRoy** [comment]
Interesting yes. Didn't know they were new features. Should have some better fallback in place there anyway. Thanks for fixing this quickly!
