### ISSUE TITLE
parse_view takes a camera

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#42]
Why is that? The view is already assigned a camera, why not use and return this?

```python
# Before
parse_view("modelPanel1", "persp")
# {"display_options": {}}

# After
parse_view("modelPanel1")
# {"camera": "persp", "display_options": {}}
```

**Comment by BigRoy** [comment]
Otherwise if you want to parse a specific camera and a specific modelPanel you'll need to ensure that camera is in that particular `modelPanel1`. This way it just makes much less assumptions and I don't have a feeling it's more complex for the artist.

**Comment by mottosso** [comment]
To me, the camera is a property of the panel.

I think the `apply_view` should also only take a panel and some options.
