### ISSUE TITLE
parse_active_scene

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#43]
### Goal

Fetch frame range and rate, and other scene-related properties used to capture.

**Comment by BigRoy** [comment]
Would `parse_active_scene()` together with `parse_active_view()` return the exact current specifications? Or would `parse_active_scene()` also retrieve the settings from a view? The latter might make too much assumptions again about what is active. Keeping them separate makes more sense to me.

```python
options = parse_active_scene()
options.update(parse_active_view())
capture(**options)
```

This would take the exact view, but also the exact frame range, render resolution, etc. Correct?

**Comment by mottosso** [comment]
Sounds good
