### ISSUE TITLE
Support for still-images

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#7]
In addition to "capture()", also provide "snap()" for single-frame captures, defaulted to compression "png".

**Comment by BigRoy** [comment]
I set up a draft in my repo for snap. Basically it wraps around `capture` so it stays in sync with the features of capture.

Note that it uses the `completeFilename` argument on the `maya.cmds.playblast` command so it saves the image out with an exact name as opposed to adding the frame number padding. This makes the code slightly more complex, but seems to the only way to override the padding. I guess the questions remains whether we prefer it to be overwritten. It does give full control over naming this way.

**Comment by mottosso** [comment]
Ah, smart. I like it.

> This makes the code slightly more complex, but seems to the only way to override the padding.

Why not keep the padding? If it aligns better with Maya overall, I see no reason to remove it. For more complex namings, I think it's okay to rely on out-of-band methods, like passing the result to `os.rename`.

Which reminds me, don't forget to return the output from `capture`. It will be the absolute path to where things went.

**Comment by BigRoy** [comment]
> Which reminds me, don't forget to return the output from capture. It will be the absolute path to where things went. 

Good catch. Forgot that one.

I have a better implementation now. The `snap()` method can have both `filename` as argument or `complete_filename` as argument. One will respectively keep the padding whereas the other will save the file out with that exact name.

Will set up a pull request now.

**Comment by mottosso** [comment]
Sounds very good

**Comment by mottosso** [comment]
Works good!
