### ISSUE TITLE
Support for Maya 2015+

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#8]
Viewport options doesn't seem to work in 2015+, it might be related to Viewport 2 and that it's the new default now.

**Comment by BigRoy** [comment]
It's not working at all? Is it ignoring the 'show' settings?

Could be the new playblast override settings that are under the *show* menu item for a *modelPanel*? 

Not sure what version of Maya they popped up, could be 2015. :)

**Comment by BigRoy** [comment]
Are you sure this is Maya 2015 only? Seems like a typo in the code?

```options = options = ViewportOptions()```

as opposed to

```options = options or ViewportOptions()```

Changing that around fixes it.

**Comment by mottosso** [comment]
I'm not sure, but that would be amazing if that's all it was!
